### ISSUE TITLE
Passing --svgo <config_file> doesn't work

### ISSUE THREAD

**Issue by SpadarShut** [boopathi/react-svg-loader#19]
I am running `npm bin/svg2react 'components/icons/menu.svg' --svgo '.svgo.yaml'` and the output doesn't respect the config file settings.

The config file looks like follows, but it can be anything, none of the settings seem to apply:
```
full: true
floatPrecision: 2
plugins:
    - removeTitle: true
    - addClassesToSVGElement:
        className: 'Icon'
    - removeAttrs:
        attrs: '(fill|stroke)'
```

I tried to rename the option `svgo` to `s` in the svg2react.js in the .bin folder and then it worked fine.
